default:
  tags:
    - docker
    - linux
    - dind

stages:
  - build-docker-image-stage
  - build-stage
  - test-stage

build-docker-image-job:
  image: docker
  stage: build-docker-image-stage
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" gitlab-intern.ait.ac.at:5010
  script:
    - tag=":dev"
    - cd .devcontainer && docker build --pull -f Dockerfile -t "$CI_REGISTRY_IMAGE${tag}" .
    - docker push "$CI_REGISTRY_IMAGE${tag}"

build-job:
  image: $CI_REGISTRY_IMAGE:dev
  stage: build-stage
  script:
    - /usr/bin/cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/gcc -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/g++ -S/builds/as/general/nonrigid_tricubic_pc_matching -B/builds/as/general/nonrigid_tricubic_pc_matching/build -G Ninja
    - /usr/bin/cmake --build /builds/as/general/nonrigid_tricubic_pc_matching/build --config Release --target all --
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - bin
    expire_in: 1 week

test-job:
  image: $CI_REGISTRY_IMAGE:dev
  stage: test-stage
  script:
    - cd test && ./test-gbpcm.sh
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - test/testdata/results
    expire_in: 1 week