default:
  tags:
    - docker
    - linux
    - dind

stages:
  - build-docker-image-stage
  - build-stage
  - test-stage

build-docker-image-job:
  image: docker
  stage: build-docker-image-stage
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" gitlab-intern.ait.ac.at:5010
  script:
    - tag=":base"
    - cd .devcontainer && docker build --pull -f Dockerfile -t "$CI_REGISTRY_IMAGE${tag}" .
    - docker push "$CI_REGISTRY_IMAGE${tag}"

build-job:
  image: $CI_REGISTRY_IMAGE:base
  stage: build-stage
  script:
    - pwd