default:
  tags:
    - docker
    - linux
    - dind

stages:
  - build-docker-image-stage
  - build-stage
  - test-stage

build-docker-image-job:
  image: docker
  stage: build-docker-image-stage
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" gitlab-intern.ait.ac.at:5010
  script:
    - tag=":dev"
    - cd .devcontainer && docker build --pull -f Dockerfile -t "$CI_REGISTRY_IMAGE${tag}" .
    - docker push "$CI_REGISTRY_IMAGE${tag}"

build-job:
  image: $CI_REGISTRY_IMAGE:dev
  stage: build-stage
  script:
    - /usr/bin/cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/gcc -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/g++ -S/builds/as/general/3D_nonrigid_tricubic_pointcloud_registration -B/builds/as/general/3D_nonrigid_tricubic_pointcloud_registration/build -G Ninja
    - /usr/bin/cmake --build /builds/as/general/3D_nonrigid_tricubic_pointcloud_registration/build --config Release --target all --
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - bin
    expire_in: 1 week

test-nordbahn-job:
  image: $CI_REGISTRY_IMAGE:dev
  stage: test-stage
  script:
    - cd test && ./test-nordbahn.sh
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - test/test-nordbahn/results
    expire_in: 1 week

test-mls-rail-job:
  image: $CI_REGISTRY_IMAGE:dev
  stage: test-stage
  script:
    - cd test && ./test-mls-rail.sh
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - test/test-mls-rail/results
    expire_in: 1 week

